### ISSUE TITLE
Does webspoon support http://localhost:8080/pentaho  for respository?

### ISSUE THREAD

**Issue by kundeng** [HiromuHota/pentaho-kettle#174]
## Expected Behavior
I'm new to this.  Is pentaho repository an enterprise only feature?  From I read,  even in the community edition,  that function still works, though at a reduced capacity.   

I clicked the connect button but it leads to an error saying it can't connect to server. 

Do I need to create a repository in advance?  If so, how?  

## Actual Behavior
Screenshots and error messages are helpful.
![image](https://user-images.githubusercontent.com/89032/62647249-1c82c380-b91e-11e9-92c4-27db3d40d346.png)

## Steps to Reproduce the Problem

  1.
  1.
  1.

### Server
  - OS (e.g., Mac OS X 10.12.6):
  - Java (e.g., Oracle JDK 8u151):
  - Servlet container (e.g., Apache Tomcat 8.5.20):
  - webSpoon (e.g., version: 0.8.0.13 or commitId: 0211d84b):

### Client
  - OS (e.g., Mac OS X 10.12.6):
  - Browser (e.g., Google Chrome 64.0.3282.140):

**Comment by HiromuHota** [comment]
No, webSpoon does not support http://localhost:8080/pentaho for repository.

Yes, even the community edition of Pentaho server (not Spoon) supports Pentaho repository. If you deploy one, webSpoon can connect to it.

**Comment by kundeng** [comment]
What is the most convenient way to do so with your docker-compose set-up?  Maybe another container running pentaho server CM edition?

**Comment by HiromuHota** [comment]
The following docker-compose.yml works.
```
version: '2' 
services:
  webspoon:
    image: hiromuhota/webspoon
    ports:
      - "8080:8080"
    links:
      - pentaho
  pentaho:
    image: doccom/pentaho-bi-server-ce
```

Use `http://pentaho:8080/pentaho` as a repository url.
